|  Column name  |  Description  |
| ----- | ------- |
| Num_posts        | Number of total posts that the user has ever posted   |
| Num_following    | Number of following                                   |
| Num_followers    | Number of followers                                   |
| Biography_length | Length (number of characters) of the user's biography |
| Picture_availability | Value 0 if the user has no profile picture, or 1 if has |
| Link_availability| Value 0 if the user has no external URL, or 1 if has |
| Average_caption_length | The average number of character of captions in media |
| Caption_zero     | Percentage (0.0 to 1.0) of captions that has almost zero (<=3) length |
| Non_image_percentage | Percentage (0.0 to 1.0) of non-image media. There are three types of media on an Instagram post, i.e. image, video, carousel
| Engagement_rate_like | Engagement rate (ER) is commonly defined as (num likes) divide by (num media) divide by (num followers)
| Engagement_rate_comment | Similar to ER like, but it is for comments |
| Location_tag_percentage | Percentage (0.0 to 1.0) of posts tagged with location |
| Average_hashtag_count   | Average number of hashtags used in a post |
| Promotional_keywords | Average use of promotional keywords in hashtag, i.e. regrann, contest, repost, giveaway, mention, share, give away, quiz |
| Followers_keywords | Average use of followers hunter keywords in hashtag, i.e. follow, like, folback, follback, f4f|
| Cosine_similarity  | Average cosine similarity of between all pair of two posts a user has |
| Post_interval      | Average interval between posts (in hours) |
| real_fake          | r (real/authentic user), f (fake user/bought followers) |

# Q1: Import labraries

In [1]:
# write your code here ^_^
import pandas as pd
import numpy as np 
import matplotlib as plt
import seaborn as sns 
%matplotlib inline

# Q2: Read instagram_users.csv file

In [2]:
# write your code here ^_^
df = pd.read_csv('instagram_users.csv')

In [3]:
df.head()

Num_posts  Num_following  Num_followers  Biography_length  \
0          44             48            325                33   
1          10             66            321               150   
2          33            970            308               101   
3          70             86            360                14   
4           3             21            285                73   

   Picture_availability  Link_availability  Average_caption_length  \
0                     1                  0                      12   
1                     1                  0                     213   
2                     1                  1                     436   
3                     1                  0                       0   
4                     1                  0                      93   

   Caption_zero  Non_image_percentage  Engagement_rate_like  \
0           0.0                   0.0                  0.00   
1           0.0                   1.0                 14.39   
2           0.0                   1.0                 10.10   
3           1.0                   0.0                  0.78   
4           0.0                   0.0                 14.29   

   Engagement_rate_comment  Location_tag_percentage  Average_hashtag_count  \
0                     0.00                    0.000                    0.0   
1                     1.97                    0.000                    1.5   
2                     0.30                    0.000                    2.5   
3                     0.06                    0.000                    0.0   
4                     0.00                    0.667                    0.0   

   Promotional_keywords  Followers_keywords  Cosine_similarity  Post_interval  \
0                   0.0               0.000           0.111111       0.094985   
1                   0.0               0.000           0.206826     230.412857   
2                   0.0               0.056           0.572174      43.569939   
3                   0.0               0.000           1.000000       5.859799   
4                   0.0               0.000           0.300494       0.126019   

  real_fake  
0      fake  
1      fake  
2      fake  
3      fake  
4      fake

# Q3: Split tha dataset into training and testing

In [4]:
# write your code here ^_^
from sklearn.model_selection import train_test_split
X = df.drop('real_fake',axis=1)
y = df['real_fake']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

# Q4: Build three machine models 

## Q4.1: The first machine model
- Print the model's name.
- Print the model's accuracy.
- Print the model's confusion matrix.

In [6]:
# write your code here ^_^
from sklearn.tree import DecisionTreeClassifier

In [7]:
dtree = DecisionTreeClassifier()

In [8]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier()

In [9]:
predictions = dtree.predict(X_test)

In [10]:
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

        fake       0.85      0.85      0.85      9524
        real       0.86      0.85      0.85      9750

    accuracy                           0.85     19274
   macro avg       0.85      0.85      0.85     19274
weighted avg       0.85      0.85      0.85     19274



In [11]:
print(confusion_matrix(y_test,predictions))

[[8142 1382]
 [1482 8268]]


## Q4.2: The second machine model
- Print the model's name.
- Print the model's accuracy.
- Print the model's confusion matrix.

In [12]:
# write your code here ^_^
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 20, criterion = 'gini', max_depth = 4) 

rfc.fit(X_train, y_train)

RandomForestClassifier(max_depth=4, n_estimators=20)

In [13]:
rfc_pred = rfc.predict(X_test)
print(confusion_matrix(y_test,rfc_pred))

[[7392 2132]
 [ 308 9442]]


In [14]:
print(classification_report(y_test,rfc_pred))

              precision    recall  f1-score   support

        fake       0.96      0.78      0.86      9524
        real       0.82      0.97      0.89      9750

    accuracy                           0.87     19274
   macro avg       0.89      0.87      0.87     19274
weighted avg       0.89      0.87      0.87     19274



In [15]:
print(accuracy_score(y_test,rfc_pred))

0.8734045864895714


## Q4.3: The third machine model
- Print the model's name.
- Print the model's accuracy.
- Print the model's confusion matrix.

In [16]:
# write your code here ^_^
from sklearn.neighbors import KNeighborsClassifier


In [17]:
k = 3

knn = KNeighborsClassifier(n_neighbors=k)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
accuracy

C:\Users\luka3\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Accuracy: 0.7328525474732801


In [18]:
cm = confusion_matrix(y_test, y_pred)
cm

[[6850 2674]
 [2475 7275]]
